# Generated by Django 3.0.5 on 2020-09-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20200916_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link avobe to read Blog Post...', max_length=255),
        ),
    ]
